In [1]:
import pandas as pd
import os
import numpy as np
import re

In [2]:
pd.set_option('display.max_columns', None)

# Data curation

##### 1. Combine dicomtocsv_series.csv and dicomtocsv_study.csv
##### 2. Group by PatientID

In [10]:
def merge_and_extract(file_path, file_series, file_study, output_file, extract_cols):
    """
    Merges two files into a single file based on shared columns, then extract desired columns
    """
    
    df_dicom_series = pd.read_csv(os.path.join(file_path, file_series))
    df_dicom_study = pd.read_csv(os.path.join(file_path, file_study))
    
    series_cols = df_dicom_series.columns
    study_cols = df_dicom_study.columns
    
    common_cols = series_cols.intersection(study_cols)
    series_not_study = series_cols.difference(study_cols)
    study_not_series = study_cols.difference(series_cols)
    
    df_all = pd.merge(df_dicom_series, df_dicom_study, how="outer", on=common_cols.to_list())
    df = df_all[extract_cols]
    
    if output_file:
        df.to_excel(output_file, index=False)
    
    return df_all, df, df_dicom_series, df_dicom_study

In [11]:
file_path = "../Data/Lee, Ju Hun's files - R3Data"

file_series = "dicomtocsv_series.csv"
file_study = "dicomtocsv_study.csv"
# output_file = "../Data/output.xlsx"

extract_cols = ['PatientID', 'AccessionNumber', 'PatientBirthDate', 'PatientAge', 'PatientSex',
        'StudyDate', 'StudyTime', 'AcquisitionDate',
        'Modality', 'Manufacturer', 'ManufacturerModelName',
        'StudyDescription', 'SeriesNumber', 'SeriesDescription',
        'Exposure',
        'Rows', 'Columns', 'PixelSpacing',
        'Modality', 'Manufacturer', 'ManufacturerModelName']

df_all, df, df_dicom_series, df_dicom_study = merge_and_extract(file_path, file_series, file_study, None, extract_cols)

In [12]:
df_dicom_series

,NumberOfReferences,ImageType,SOPClassUID,StudyDate,AcquisitionDate,AcquisitionDateTime,StudyTime,AccessionNumber,Modality,Manufacturer,StudyDescription,SeriesDescription,ManufacturerModelName,PatientName,PatientID,IssuerOfPatientID,PatientBirthDate,PatientSex,OtherPatientIDs,ScanningSequence,SequenceVariant,ScanOptions,MRAcquisitionType,SequenceName,SliceThickness,MagneticFieldStrength,SpacingBetweenSlices,ProtocolName,Exposure,ConvolutionKernel,MREchoSequence,StudyInstanceUID,SeriesInstanceUID,StudyID,SeriesNumber,InstanceNumber,NumberOfFrames,Rows,Columns,PixelSpacing,BurnedInAnnotation,WindowCenterWidthExplanation,TransferSyntaxUID
0,1,DERIVED\PRIMARY,1.2.840.10008.5.1.4.1.1.1.2,2015-01-02,2015-01-02,NaN,08:39:23,80861023,MG,"HOLOGIC, Inc.",BREAST IMAGING TOMOSYNTHESIS DIAGNOSTIC BILATERAL,L ISO,Selenia Dimensions,NaN,4333469193,NaN,1964-07-01,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,NaN,NaN,1.400756,1.882280,1.113140,71100000.0,367.0,NaN,4096.0,3328.0,0.065238\0.065238,NaN,NaN,1.2.840.10008.1.2.4.70
1,1,DERIVED\SECONDARY,1.2.840.10008.5.1.4.1.1.7,2015-01-02,NaN,NaN,11:30:52,81776067,MG,"R2 Technology, Inc.",DIAG MAMMO - DIRECT DIG IMAGE BIL ALL VIEWS,R2 CAD SC,Cenova,NaN,4333843993,NaN,1967-07-01,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.233100,1.347473,1.119129,1.0,1.0,NaN,1500.0,1250.0,NaN,NaN,NaN,1.2.840.10008.1.2.1
2,1,DERIVED\PRIMARY,1.2.840.10008.5.1.4.1.1.1.2,2015-01-02,2015-01-02,NaN,11:30:52,81776067,MG,"HOLOGIC, Inc.",MAMMOGRAM DIGITAL DX BILAT,L CC,Selenia Dimensions,NaN,4333843993,NaN,1967-07-01,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,246.0,NaN,NaN,1.233100,1.936507,1.119129,71300000.0,87.0,NaN,4096.0,3328.0,0.065238\0.065238,NaN,NaN,1.2.840.10008.1.2.4.70
3,1,DERIVED\PRIMARY,1.2.840.10008.5.1.4.1.1.1.2,2015-01-02,2015-01-02,NaN,11:30:52,81776067,MG,"HOLOGIC, Inc.",MAMMOGRAM DIGITAL DX BILAT,L MLO,Selenia Dimensions,NaN,4333843993,NaN,1967-07-01,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,250.0,NaN,NaN,1.233100,1.220605,1.119129,71300000.0,93.0,NaN,4096.0,3328.0,0.065238\0.065238,NaN,NaN,1.2.840.10008.1.2.4.70
4,1,DERIVED\PRIMARY,1.2.840.10008.5.1.4.1.1.1.2,2015-01-02,2015-01-02,NaN,11:30:52,81776067,MG,"HOLOGIC, Inc.",MAMMOGRAM DIGITAL DX BILAT,R CC,Selenia Dimensions,NaN,4333843993,NaN,1967-07-01,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,197.0,NaN,NaN,1.233100,1.340178,1.119129,71300000.0,75.0,NaN,4096.0,3328.0,0.065238\0.065238,NaN,NaN,1.2.840.10008.1.2.4.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136194,1,DERIVED\SECONDARY,1.2.840.10008.5.1.4.1.1.7,2022-12-29,NaN,NaN,03:17:31,451098158,MG,"HOLOGIC, Inc.",DIAGNOSTIC RIGHT UNILATERAL MAMMOGRAM WITH TOMO,Hologic R2 ImageChecker CAD SC,Selenia Dimensions,NaN,4333211581,NaN,1947-07-01,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.114255,1.277641,1.310636,745.0,1.0,NaN,1500.0,1250.0,NaN,NaN,NaN,1.2.840.10008.1.2.1
136195,1,DERIVED\PRIMARY,1.2.840.10008.5.1.4.1.1.1.2,2022-12-29,2022-12-29,NaN,03:17:30,451098158,MG,"HOLOGIC, Inc.",DIAGNOSTIC RIGHT UNILATERAL MAMMOGRAM WITH TOMO,R ML,Selenia Dimensions,NaN,4333211581,NaN,1947-07-01,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.0,NaN,NaN,1.114255,1.336870,1.310636,71100000.0,427.0,NaN,3328.0,2560.0,0.038889\0.038889,NaN,NaN,1.2.840.10008.1.2.4.70
136196,1,DERIVED\PRIMARY,1.2.840.10008.5.1.4.1.1.1.2,2022-12-29,2022-12-29,NaN,03:17:30,451098158,MG,"HOLOGIC, Inc.",DIAGNOSTIC RIGHT UNILATERAL MAMMOGRAM WITH TOMO,R CC,Selenia Dimensions,NaN,4333211581,NaN,1947-07-01,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109.0,NaN,NaN,1.114255,1.140919,1.310636,71100000.0,425.0,NaN,3328.0,2560.0,0.038889\0.038889,NaN,NaN,1.2.840.10008.1.2.4.70
136197,1,DERIVED\PRIMARY\TOMOSYNTHESIS\GENERATED_2D,1.2.840.10008.5.1.4.1.1.1.2,2022-12-29,NaN,NaN,03:17:30,451098158,MG,"HOLOGIC, Inc.",DIAGNOSTIC RIGHT UNILATERAL MAMMOGRAM WITH TOMO,R MLO Intelligent 2D,Selenia Dimensions,NaN,4333211581,NaN,1947-07-01,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.0,NaN,NaN,1.114255,1.278132,1.310636,71300000.0,422.0,NaN,3328.0,2560.0,0.064744\0.064744,NaN,Normal\High contrast\Low contrast,1.2.840.10008.1.2.4.70
136198,1,DERIVED\PRIMARY\TOMOSYNTHESIS\GENERATED_2D,1.2.840.10008.5.1.4.1.1.1.2,2022-12-29,NaN,NaN,03:17:30,451098158,MG,"HOLOGIC, Inc.",DIAGNOSTIC RIGHT UNILATERAL MAMMOGRAM WITH TOMO,R CC Intelligent 2D,Selenia Dimensions,NaN,4333211581,NaN,1947-07-01,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,NaN,NaN,1.114255,1.180501,1.310636,71300000.0,415.0,NaN,3328.0,2560.0,0.065045\0.065045,NaN,Normal\High contrast\Low contrast,1.2.840.10008.1.2.4.70

In [13]:
df_dicom_study

,StudyDate,StudyTime,AccessionNumber,Modality,Manufacturer,InstitutionName,InstitutionAddress,StationName,StudyDescription,InstitutionalDepartmentName,PerformingPhysicianName,ManufacturerModelName,PatientName,PatientID,IssuerOfPatientID,PatientBirthDate,PatientSex,OtherPatientIDs,PatientAge,BodyPartExamined,ProtocolName,StudyInstanceUID,StudyStatusID
0,2015-01-02,08:39:23,80861023,MG,"HOLOGIC, Inc.",NaN,NaN,NaN,BREAST IMAGING TOMOSYNTHESIS DIAGNOSTIC BILATERAL,NaN,NaN,Selenia Dimensions,NaN,4333469193,NaN,1964-07-01,F,NaN,050Y,BREAST,NaN,1.400756,NaN
1,2015-01-02,11:30:52,81776067,MG,"R2 Technology, Inc.",NaN,NaN,NaN,DIAG MAMMO - DIRECT DIG IMAGE BIL ALL VIEWS,NaN,NaN,Cenova,NaN,4333843993,NaN,1967-07-01,F,NaN,047Y,BREAST,NaN,1.233100,NaN
2,2015-01-02,13:47:42,80984343,MG,"R2 Technology, Inc.",NaN,NaN,NaN,DIAG MAMMO - DIRECT DIG IMAGE LT ALL VIEWS,NaN,NaN,Cenova,NaN,4334188890,NaN,1935-07-01,F,NaN,079Y,BREAST,NaN,1.115858,NaN
3,2015-01-02,18:52:08,80861023,MG,"R2 Technology, Inc.",NaN,NaN,NaN,BREAST IMAGING TOMOSYNTHESIS DIAGNOSTIC BILATERAL,NaN,NaN,Cenova,NaN,4333469193,NaN,1964-07-01,F,NaN,050Y,BREAST,NaN,1.328263,NaN
4,2015-01-05,02:21:18,80113862,MG,"R2 Technology, Inc.",NaN,NaN,NaN,SCREENING MAMMOGRAPHY DIGITAL BILAT ALL VIEWS ...,NaN,NaN,Cenova,NaN,4333966965,NaN,1950-07-01,F,NaN,064Y,BREAST,NaN,1.143213,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15556,2022-12-13,02:14:40,459321381,MG,"HOLOGIC, Inc.",NaN,NaN,NaN,SCREENING MAMMO WITH TOMO,NaN,NaN,Selenia Dimensions,NaN,4333662111,NaN,1977-07-01,F,NaN,045Y,BREAST,NaN,1.654537,NaN
15557,2022-12-19,11:38:02,450005908,MG,"HOLOGIC, Inc.",NaN,NaN,NaN,SCREENING MAMMOGRAM WITH TOMO,NaN,NaN,Selenia Dimensions,NaN,4333233282,NaN,1957-07-01,F,NaN,064Y,BREAST,NaN,1.122824,NaN
15558,2022-12-22,18:46:26,459297287,MG,"HOLOGIC, Inc.",NaN,NaN,NaN,SCREENING MAMMOGRAPHY DIGITAL BILATERAL W TOMO,NaN,NaN,Selenia Dimensions,NaN,4333740431,NaN,1963-07-01,F,NaN,059Y,BREAST,NaN,1.177395,NaN
15559,2022-12-28,11:37:53,459166823,MG,"HOLOGIC, Inc.",NaN,NaN,NaN,SCREENING MAMMOGRAM WITH TOMO,NaN,NaN,Selenia Dimensions,NaN,4333966333,NaN,1960-07-01,F,NaN,062Y,BREAST,NaN,1.309485,NaN
15560,2022-12-29,03:17:30,451098158,MG,"HOLOGIC, Inc.",NaN,NaN,NaN,DIAGNOSTIC RIGHT UNILATERAL MAMMOGRAM WITH TOMO,NaN,NaN,Selenia Dimensions,NaN,4333211581,NaN,1947-07-01,F,NaN,075Y,BREAST,NaN,1.114255,NaN

In [14]:
def group_by_patient(df, output_file):
    """
    Group dataframe by patient ID
    """    
    PIDs = df["PatientID"].unique()
    num_patient = PIDs.size
    
    count = 0
    for pid in PIDs:
        if count == 0: 
            tmp = df[df["PatientID"] == pid]
        else: 
            tmp = pd.concat([tmp, df[df["PatientID"] == pid]], ignore_index=True)
        count += 1
    
#     tmp.sort_values(by=['PatientID', 'StudyDate'], inplace=True, ignore_index=True)
    tmp.sort_values(by=['PatientID', 'StudyDate', 'AccessionNumber'], inplace=True, ignore_index=True)
    
    if output_file:
        tmp.to_excel(output_file, index=False)
    
    return num_patient, tmp

In [15]:
output_file = "../Data/dicom.xlsx"
num_patient, output = group_by_patient(df, None)

# **Add tags** (Study, Side, Series)

### <span style="color:#FF6347;">**READ**</span> file

In [3]:
file_path = "../Data/dicom.xlsx"
dicom = pd.read_excel(file_path)

In [4]:
dicom

,PatientID,AccessionNumber,PatientBirthDate,PatientAge,PatientSex,StudyDate,StudyTime,AcquisitionDate,Modality,Manufacturer,ManufacturerModelName,StudyDescription,SeriesNumber,SeriesDescription,Exposure,Rows,Columns,PixelSpacing
0,4330018595,60103700,1965-07-01,054Y,F,2020-06-02,09:10:52,NaN,MG,"R2 Technology, Inc.",Cenova,DIAG DIG MAMMO RIGHT ALL VIEWS WITH TOMOSYNTHESIS,1.0,Hologic R2 ImageChecker CAD SC,NaN,1500.0,1250.0,NaN
1,4330018595,60103700,1965-07-01,NaN,F,2020-06-02,09:10:51,NaN,MG,"R2 Technology, Inc.",Cenova,DIAG DIG MAMMO RIGHT ALL VIEWS WITH TOMOSYNTHESIS,1.0,Hologic R2 ImageChecker CAD SC,NaN,1500.0,1250.0,NaN
2,4330018595,60103700,1965-07-01,NaN,F,2020-06-02,09:10:51,2020-06-02,MG,"HOLOGIC, Inc.",Selenia Dimensions,DIAG DIG MAMMO RIGHT ALL VIEWS WITH TOMOSYNTHESIS,71100000.0,R ML,126.0,3328.0,2560.0,0.038889\0.038889
3,4330018595,60103700,1965-07-01,NaN,F,2020-06-02,09:10:51,NaN,MG,"HOLOGIC, Inc.",Selenia Dimensions,DIAG DIG MAMMO RIGHT ALL VIEWS WITH TOMOSYNTHESIS,71300000.0,R XCCL Intelligent 2D,63.0,3328.0,2560.0,0.064318\0.064318
4,4330018595,60103700,1965-07-01,NaN,F,2020-06-02,09:10:51,NaN,MG,"HOLOGIC, Inc.",Selenia Dimensions,DIAG DIG MAMMO RIGHT ALL VIEWS WITH TOMOSYNTHESIS,71300000.0,R ML Intelligent 2D,57.0,3328.0,2560.0,0.064619\0.064619
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136228,4339959661,62216536,1971-07-01,NaN,F,2019-10-28,02:45:37,2019-10-28,MG,"HOLOGIC, Inc.",Selenia Dimensions,SCREENING MAMMOGRAPHY DIGITAL BILATERAL W TOMOSYN,72100000.0,L CC Tomosynthesis Projection,72.0,425.0,266.0,NaN
136229,4339959661,62216536,1971-07-01,NaN,F,2019-10-28,02:45:37,2019-10-28,MG,"HOLOGIC, Inc.",Selenia Dimensions,SCREENING MAMMOGRAPHY DIGITAL BILATERAL W TOMOSYN,72100000.0,R CC Tomosynthesis Projection,74.0,425.0,266.0,NaN
136230,4339959661,62216536,1971-07-01,NaN,F,2019-10-28,02:45:37,2019-10-28,MG,"HOLOGIC, Inc.",Selenia Dimensions,SCREENING MAMMOGRAPHY DIGITAL BILATERAL W TOMOSYN,72100000.0,L MLO Tomosynthesis Projection,78.0,425.0,266.0,NaN
136231,4339959661,62216536,1971-07-01,NaN,F,2019-10-28,18:20:08,NaN,PR,Philips Medical Systems,iSite Enterprise,SCREENING MAMMOGRAPHY DIGITAL BILATERAL W TOMOSYN,1.0,5DBAD14E0,NaN,NaN,NaN,NaN
136232,4339959661,62216536,1971-07-01,NaN,F,2019-10-28,18:20:08,NaN,PR,Philips Medical Systems,iSite Enterprise,SCREENING MAMMOGRAPHY DIGITAL BILATERAL W TOMOSYN,1.0,5DBAD14E0,NaN,NaN,NaN,NaN

In [5]:
dicom["Modality"].unique()

array(['MG', 'PR', 'SR', 'US', 'MR', 'OT', 'KO', 'SC'], dtype=object)

In [6]:
laterality_bi = ["BILATERAL", "BILAT", "BIL", "BI"]
laterality_uni = ["UNILATERAL", "UNILAT", "UNI", "Unilateral"]
other = ["IMPLANT", "CONTRAST ENHANCED", "Implant"]

In [7]:
dicom_copy = dicom.copy()

### <span style="color:blue"> **Study**</span> (SCREEN, DIAG)

In [8]:
study_screen = ["SCREENING", "SCREEN", "Screening"]
study_diag = ["DIAG", "DIAGNOSTIC", "DX", "Diagnostic"]

In [9]:
# Assuming your DataFrame is named 'df' and the column where you found the words is 'Notes'
column_to_check = 'StudyDescription' 
type_column = 'study'

# Ensure the column is treated as strings and handle missing values
dicom_copy[column_to_check] = dicom_copy[column_to_check].astype(str)

# ---Create the OR-Condition Mask ---
# The pattern uses the '|' (OR) symbol.
# We use .str.contains() with case=False to handle both "DIAG" and "Diagnostic".
diag_terms = [term for term in study_diag]
diag_pattern = '|'.join([re.escape(term) for term in diag_terms])

screen_terms = [term for term in study_screen]
screen_pattern = '|'.join([re.escape(term) for term in screen_terms])

# Create a boolean mask: True if the string contains either word (case-insensitive)
diag_mask = dicom_copy[column_to_check].str.contains(diag_pattern, case=False, na=False, regex=True)
screen_mask = dicom_copy[column_to_check].str.contains(screen_pattern, case=False, na=False, regex=True)

# --- Assign the value "DIAG" to the 'type' column ---
# Use .loc to assign the value only where the mask is True
dicom_copy.loc[diag_mask, type_column] = "DIAG"
dicom_copy.loc[screen_mask, type_column] = "SCREEN"

### <span style="color:blue">**Side**</span> (R, L)

In [10]:
side_right = ["RIGHT", "RT", "Right", "R XCCL", "R MLO", "R CC", "R ML", "R SIO", "R LM"]
side_left = ["LEFT", "LT", "Left", "L XCCL", "L MLO", "L CC", "L ML", "L SIO", "L LM"]

In [11]:
# Assuming your DataFrame is named 'df' and the column where you found the words is 'Notes'
column_to_check = 'SeriesDescription' 
type_column = 'side'

# Ensure the column is treated as strings and handle missing values
dicom_copy[column_to_check] = dicom_copy[column_to_check].astype(str)

# ---Create the OR-Condition Mask ---
# The pattern uses the '|' (OR) symbol.
# We use .str.contains() with case=False to handle both "DIAG" and "Diagnostic".
side_right_terms = [term for term in side_right]
side_right_pattern = '|'.join([re.escape(term) for term in side_right_terms])

side_left_terms = [term for term in side_left]
side_left_pattern = '|'.join([re.escape(term) for term in side_left_terms])

# Create a boolean mask: True if the string contains either word (case-insensitive)
side_right_mask = dicom_copy[column_to_check].str.contains(side_right_pattern, case=False, na=False, regex=True)
side_left_mask = dicom_copy[column_to_check].str.contains(side_left_pattern, case=False, na=False, regex=True)


# --- Assign the value "DIAG" to the 'type' column ---
# Use .loc to assign the value only where the mask is True
dicom_copy.loc[side_right_mask, type_column] = "R"
dicom_copy.loc[side_left_mask, type_column] = "L"

### <span style="color:blue">**Series**</span> (DBT, IN2D, C VIEW, SECURE)

In [12]:
series_dbt = ["TOMOSYNTHESIS", "TOMOSYN", "TOMO", "TOMOHD", "TomoHD", "Tomosynthesis"]
series_in2d = ["Intelligent 2D"]
series_cview = ["C-View"]
series_secure = ["SecurView"]

In [13]:
# Assuming your DataFrame is named 'df' and the column where you found the words is 'Notes'
column_to_check = 'SeriesDescription' 
type_column = 'series'

# Ensure the column is treated as strings and handle missing values
dicom_copy[column_to_check] = dicom_copy[column_to_check].astype(str)

# ---Create the OR-Condition Mask ---
# The pattern uses the '|' (OR) symbol.
dbt_terms = [term for term in series_dbt]
dbt_pattern = '|'.join([re.escape(term) for term in dbt_terms])

in2d_terms = [term for term in series_in2d]
in2d_pattern = '|'.join([re.escape(term) for term in in2d_terms])

cview_terms = [term for term in series_cview]
cview_pattern = '|'.join([re.escape(term) for term in cview_terms])

secure_terms = [term for term in series_secure]
secure_pattern = '|'.join([re.escape(term) for term in secure_terms])

# Create a boolean mask: True if the string contains either word (case-insensitive)
dbt_mask = dicom_copy[column_to_check].str.contains(dbt_pattern, case=False, na=False, regex=True)
in2d_mask = dicom_copy[column_to_check].str.contains(in2d_pattern, case=False, na=False, regex=True)
cview_mask = dicom_copy[column_to_check].str.contains(cview_pattern, case=False, na=False, regex=True)
secure_mask = dicom_copy[column_to_check].str.contains(secure_pattern, case=False, na=False, regex=True)

# --- Assign the value "DBT" to the 'type' column ---
# Use .loc to assign the value only where the mask is True
dicom_copy.loc[dbt_mask, type_column] = "DBT"
dicom_copy.loc[in2d_mask, type_column] = "IN2D"
dicom_copy.loc[cview_mask, type_column] = "C VIEW"
dicom_copy.loc[secure_mask, type_column] = "SECURE"

In [14]:
dicom_copy

,PatientID,AccessionNumber,PatientBirthDate,PatientAge,PatientSex,StudyDate,StudyTime,AcquisitionDate,Modality,Manufacturer,ManufacturerModelName,StudyDescription,SeriesNumber,SeriesDescription,Exposure,Rows,Columns,PixelSpacing,study,side,series
0,4330018595,60103700,1965-07-01,054Y,F,2020-06-02,09:10:52,NaN,MG,"R2 Technology, Inc.",Cenova,DIAG DIG MAMMO RIGHT ALL VIEWS WITH TOMOSYNTHESIS,1.0,Hologic R2 ImageChecker CAD SC,NaN,1500.0,1250.0,NaN,DIAG,NaN,NaN
1,4330018595,60103700,1965-07-01,NaN,F,2020-06-02,09:10:51,NaN,MG,"R2 Technology, Inc.",Cenova,DIAG DIG MAMMO RIGHT ALL VIEWS WITH TOMOSYNTHESIS,1.0,Hologic R2 ImageChecker CAD SC,NaN,1500.0,1250.0,NaN,DIAG,NaN,NaN
2,4330018595,60103700,1965-07-01,NaN,F,2020-06-02,09:10:51,2020-06-02,MG,"HOLOGIC, Inc.",Selenia Dimensions,DIAG DIG MAMMO RIGHT ALL VIEWS WITH TOMOSYNTHESIS,71100000.0,R ML,126.0,3328.0,2560.0,0.038889\0.038889,DIAG,R,NaN
3,4330018595,60103700,1965-07-01,NaN,F,2020-06-02,09:10:51,NaN,MG,"HOLOGIC, Inc.",Selenia Dimensions,DIAG DIG MAMMO RIGHT ALL VIEWS WITH TOMOSYNTHESIS,71300000.0,R XCCL Intelligent 2D,63.0,3328.0,2560.0,0.064318\0.064318,DIAG,R,IN2D
4,4330018595,60103700,1965-07-01,NaN,F,2020-06-02,09:10:51,NaN,MG,"HOLOGIC, Inc.",Selenia Dimensions,DIAG DIG MAMMO RIGHT ALL VIEWS WITH TOMOSYNTHESIS,71300000.0,R ML Intelligent 2D,57.0,3328.0,2560.0,0.064619\0.064619,DIAG,R,IN2D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136228,4339959661,62216536,1971-07-01,NaN,F,2019-10-28,02:45:37,2019-10-28,MG,"HOLOGIC, Inc.",Selenia Dimensions,SCREENING MAMMOGRAPHY DIGITAL BILATERAL W TOMOSYN,72100000.0,L CC Tomosynthesis Projection,72.0,425.0,266.0,NaN,SCREEN,L,DBT
136229,4339959661,62216536,1971-07-01,NaN,F,2019-10-28,02:45:37,2019-10-28,MG,"HOLOGIC, Inc.",Selenia Dimensions,SCREENING MAMMOGRAPHY DIGITAL BILATERAL W TOMOSYN,72100000.0,R CC Tomosynthesis Projection,74.0,425.0,266.0,NaN,SCREEN,R,DBT
136230,4339959661,62216536,1971-07-01,NaN,F,2019-10-28,02:45:37,2019-10-28,MG,"HOLOGIC, Inc.",Selenia Dimensions,SCREENING MAMMOGRAPHY DIGITAL BILATERAL W TOMOSYN,72100000.0,L MLO Tomosynthesis Projection,78.0,425.0,266.0,NaN,SCREEN,L,DBT
136231,4339959661,62216536,1971-07-01,NaN,F,2019-10-28,18:20:08,NaN,PR,Philips Medical Systems,iSite Enterprise,SCREENING MAMMOGRAPHY DIGITAL BILATERAL W TOMOSYN,1.0,5DBAD14E0,NaN,NaN,NaN,NaN,SCREEN,NaN,NaN
136232,4339959661,62216536,1971-07-01,NaN,F,2019-10-28,18:20:08,NaN,PR,Philips Medical Systems,iSite Enterprise,SCREENING MAMMOGRAPHY DIGITAL BILATERAL W TOMOSYN,1.0,5DBAD14E0,NaN,NaN,NaN,NaN,SCREEN,NaN,NaN

### <span style="color:#FF6347;">**SAVE**</span> file

In [15]:
output_file = os.path.join("../Data/",'dicom_tag' + ".xlsx")
dicom_copy.to_excel(output_file, index=False)

### <span style="color:#FF6347;">**READ**</span> file

In [4]:
file_path = os.path.join("../Data/",'dicom_tag' + ".xlsx")
dicom = pd.read_excel(file_path)

In [6]:
dicom[dicom["series"]=="DBT"]["PatientID"].unique().size

759