In [1]:
import pandas as pd
import os

In [2]:
pd.set_option('display.max_columns', None)

### Files

See **parameter explanation for detail information

In [3]:
file_path = "P:/Dataset/R01-MO-DBT/MO-DBT-data-curation/parameters of interest.xlsx"
files = pd.ExcelFile(file_path).sheet_names

In [4]:
files

['enteredit_findings',
 'pathology',
 'pathology_findings',
 'patient_data_ie',
 'hormonal_mens',
 'risk_factors',
 'vitals',
 'patient_demo',
 'procedure_notes']

In [5]:
shared_path = "P:/Dataset/R01-MO-DBT/MO-DBT-data-curation/R3Data"

### 2. pathology_findings 
<span style="color: blue;">Change idx value **based on EHR file**</span>

In [7]:
idx = 3
file = files[idx-1]
print(file)
extract_cols = pd.read_excel(file_path, sheet_name=file)["Name"].tolist()
print(extract_cols)

pathology_findings
['PATIENT_STUDY_ID', 'BX_ID', 'PATHOLOGY_DATE', 'LESION_CLASS', 'PATHOLOGY_CD', 'HISTROLOGY_GRADE', 'ESTROGEN_RECEPTOR', 'PROGESTERONE_RECEPTOR', 'HER2NEU', 'STAGE_T', 'STAGE_N', 'STAGE_M', 'STAGE_NUM', 'MARGIN_STATUS']

In [8]:
file_names = [
    str(file) + ".txt", 
    str(file) + ".csv",
    str(file) + ".csv"
]
file_names

['pathology_findings.txt', 'pathology_findings.csv', 'pathology_findings.csv']

### Cancer

In [9]:
study = "Cancer"
folder = ["R3_3787_Lee_Cancer_Extract_Files", "R3_3787_Lee_Data_Cancer_20240509", "R3_3787_Lee_Data_Cancer_20250912"]

In [10]:
final_unique_dfs = [] # List to hold the de-duplicated data from each file

# 2. Process each file
for i, file_name in enumerate(file_names):
    file_extension = os.path.splitext(file_name)[1].lower()
    file_path = os.path.join(shared_path, study, folder[i], file_name)
    
    if file_extension == '.csv':
        try:
            current_df = pd.read_csv(file_path, encoding='latin-1')
        except:
            print('file not exist in:', folder[i])
    elif file_extension == '.txt':
        try:
            current_df = pd.read_csv(file_path, sep='|')
        except:
            print('file not exist in:', folder[i])
    else:
        continue

    # --- KEY LOGIC FOR INTER-FILE DEDUPLICATION ---
    
    # Concatenate the current file's data with all previously processed data
    # (Do NOT use ignore_index=True here, we need separate indices for now)
    
    if final_unique_dfs:
        # Create a temporary DataFrame of ALL data processed so far
        all_prior_data = pd.concat(final_unique_dfs)
        
        # Check the current_df against all prior data. 
        # We only look at the columns that contain the actual data (excluding the index).
        data_columns = current_df.columns
        
        # Identify rows in the current file that are NOT duplicates of PRIOR files
        # The 'indicator=True' is used to identify the source of the merge
        merged = pd.merge(
            current_df, 
            all_prior_data, 
            on=list(data_columns), # Merge on all data columns
            how='left', 
            indicator=True
        )
        
        # Rows in the current file that are *only* in the 'left' (current_df) are unique
        unique_to_current_file = merged[merged['_merge'] == 'left_only'].drop(columns='_merge')
        
        # Append the unique data (which includes any intra-file duplicates)
        final_unique_dfs.append(unique_to_current_file)
    else:
        # The first file is added as is (it has no prior files to check against)
        final_unique_dfs.append(current_df)


# 3. Final Concatenation
if final_unique_dfs:
    # Concatenate the final list of DataFrames to produce the result
    final_df = pd.concat(final_unique_dfs, ignore_index=True)

    print("✅ Successfully merged and removed ONLY inter-file duplicates.")
    print("\nFinal DataFrame head (includes intra-file duplicates):")
else:
    print("❌ No valid files were read. The final DataFrame is empty.")

✅ Successfully merged and removed ONLY inter-file duplicates.

Final DataFrame head (includes intra-file duplicates):

In [11]:
final_df

,PATIENT_STUDY_ID,BX_ID,PATHOLOGY_DATE,PATIENT_ID,FINDING_ID,PATHOLOGY_CD,LESION_CLASS,FINDING_SIZE_1,FINDING_SIZE_2,MEASUREMENT_TYPE,HISTROLOGY_GRADE,NODES_REMOVED,NODES_POSITIVE,MARGIN_STATUS,ESTROGEN_RECEPTOR,PROGESTERONE_RECEPTOR,HER2NEU,STAGE_T,STAGE_N,STAGE_M,STAGE_NUM,NIPPLE_INVOLVED
0,4337721563,482678,01/09/2020,42254322,163533,DCH,MALIGN,NaN,NaN,NaN,G3,NaN,NaN,NaN,P,N,NaN,Ductal carcinoma in situ,NaN,NaN,Stage 0,N
1,4333499919,481991,02/06/2020,741762,164211,FC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
2,4333872128,481997,02/06/2020,3124344,164215,ID,MALIGN,22.0,NaN,Radiologic,G3,2.0,0.0,NaN,P,P,P,Tumor more than 5 cm in greatest dimension,No regional lymph node metastasis,NaN,Stage 3B,N
3,4333872128,481997,02/06/2020,3124344,164215,DCI,MALIGN,22.0,NaN,Radiologic,G3,2.0,0.0,NaN,P,P,P,Tumor more than 5 cm in greatest dimension,No regional lymph node metastasis,NaN,Stage 3B,N
4,4333872128,481996,02/06/2020,3124344,164216,ID,MALIGN,22.0,NaN,Radiologic,G3,2.0,0.0,NaN,P,P,P,Tumor more than 5 cm in greatest dimension,No regional lymph node metastasis,NaN,Stage 3B,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18391,4335673096,352938,11/28/2022,6719081,192986,FA,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
18392,4333689962,350553,12/14/2022,2142937,194360,ID,MALIGN,19.0,NaN,Pathologic,G2,2.0,0.0,NaN,P,N,N,Tumor more than 1 cm but not more than 2 cm in...,No regional lymph node metastasis,Distant metastasis cannot be assessed,Stage 1,N
18393,4333689962,350553,12/14/2022,2142937,194360,II,MALIGN,19.0,NaN,Pathologic,G2,2.0,0.0,NaN,P,N,N,Tumor more than 1 cm but not more than 2 cm in...,No regional lymph node metastasis,Distant metastasis cannot be assessed,Stage 1,N
18394,4334447886,350012,12/16/2022,1635124,194901,IL,MALIGN,6.0,NaN,Pathologic,G2,NaN,NaN,NaN,P,N,NaN,Tumor more than 0.5 cm but not more than 1 cm ...,"Regional lymph nodes cannot be assessed (e.g.,...",NaN,Stage 1,N
18395,4334273730,350092,12/05/2022,7653222,194921,FA,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N

In [12]:
final_df['PATHOLOGY_DATE'] = pd.to_datetime(final_df['PATHOLOGY_DATE'], format='%m/%d/%Y')
final_df['PATHOLOGY_DATE'] = final_df['PATHOLOGY_DATE'].dt.strftime('%Y-%m-%d')

In [13]:
final_df.sort_values(by=['PATIENT_STUDY_ID', 'PATHOLOGY_DATE', 'BX_ID'], ascending=[True, True, False], inplace=True, ignore_index=True)

#### <span style="color: blue;">Remove duplicated entries, add a column marked how many duplicates </span> 

**Before drop duplicate = <span style="color: blue;">final_df</span> , after drop duplicate = <span style="color: blue;">unique_df</span>**

In [14]:
unique_df = final_df.copy()

In [15]:
unique_df['duplicate_count'] = unique_df.groupby(unique_df.columns.tolist(), dropna=False).transform('size')

In [16]:
unique_df = unique_df.drop_duplicates(subset=unique_df.columns.tolist(), keep = 'first').reset_index(drop = True)

In [17]:
unique_extract_cols = extract_cols + ['duplicate_count']

In [18]:
unique_df[unique_df["PATIENT_STUDY_ID"]==4330018595]

,PATIENT_STUDY_ID,BX_ID,PATHOLOGY_DATE,PATIENT_ID,FINDING_ID,PATHOLOGY_CD,LESION_CLASS,FINDING_SIZE_1,FINDING_SIZE_2,MEASUREMENT_TYPE,HISTROLOGY_GRADE,NODES_REMOVED,NODES_POSITIVE,MARGIN_STATUS,ESTROGEN_RECEPTOR,PROGESTERONE_RECEPTOR,HER2NEU,STAGE_T,STAGE_N,STAGE_M,STAGE_NUM,NIPPLE_INVOLVED,duplicate_count
0,4330018595,487690,2020-06-05,9654707,168529,ID,MALIGN,30.0,NaN,Pathologic,G2,2.0,0.0,NaN,P,P,N,Tumor more than 1 cm but not more than 2 cm in...,No regional lymph node metastasis,No distant metastasis,Stage 1,N,1
1,4330018595,487690,2020-06-05,9654707,168529,DCI,MALIGN,30.0,NaN,Pathologic,G2,2.0,0.0,NaN,P,P,N,Tumor more than 1 cm but not more than 2 cm in...,No regional lymph node metastasis,No distant metastasis,Stage 1,N,1
2,4330018595,475789,2020-07-28,9654707,170446,II,MALIGN,30.0,NaN,Pathologic,G2,2.0,0.0,NaN,P,P,N,Tumor more than 1 cm but not more than 2 cm in...,No regional lymph node metastasis,No distant metastasis,Stage 1,N,1

In [19]:
unique_df['duplicate_count'].unique()

array([1, 2, 3], dtype=int64)

In [20]:
unique_df[unique_df['duplicate_count']!=1]

,PATIENT_STUDY_ID,BX_ID,PATHOLOGY_DATE,PATIENT_ID,FINDING_ID,PATHOLOGY_CD,LESION_CLASS,FINDING_SIZE_1,FINDING_SIZE_2,MEASUREMENT_TYPE,HISTROLOGY_GRADE,NODES_REMOVED,NODES_POSITIVE,MARGIN_STATUS,ESTROGEN_RECEPTOR,PROGESTERONE_RECEPTOR,HER2NEU,STAGE_T,STAGE_N,STAGE_M,STAGE_NUM,NIPPLE_INVOLVED,duplicate_count
170,4330375231,487557,2019-11-14,45028177,167571,FC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
171,4330375231,487557,2019-11-14,45028177,167572,FC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
295,4330460996,427070,2018-11-05,43212929,130325,RS,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
296,4330460996,427070,2018-11-05,43212929,130326,FF,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
297,4330460996,427070,2018-11-05,43212929,130325,SA,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
2512,4333186149,470719,2021-02-22,2712006,175346,LS,HIGHRISK,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
2513,4333186149,470719,2021-02-22,2712006,175347,ALH,HIGHRISK,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
4283,4333370935,412539,2019-03-04,1074757,133887,DHU,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
4284,4333370935,412539,2019-03-04,1074757,133888,DHU,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
8408,4333835305,486771,2020-02-13,2564015,169455,FC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
8409,4333835305,486771,2020-02-13,2564015,169455,AD,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
8410,4333835305,486771,2020-02-13,2564015,169454,AD,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
8411,4333835305,486771,2020-02-13,2564015,169454,FC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
9282,4333910662,440152,2017-07-27,2075023,107028,II,MALIGN,5.0,NaN,Pathologic,G2,2.0,0.0,NaN,P,P,N,Tumor more than 0.1 cm but not more than 0.5 c...,No regional lymph node metastasis,Distant metastasis cannot be assessed,Stage 1,N,2
9283,4333910662,440152,2017-07-27,2075023,107029,II,MALIGN,5.0,NaN,Pathologic,G2,2.0,0.0,NaN,P,P,N,Tumor more than 0.1 cm but not more than 0.5 c...,No regional lymph node metastasis,Distant metastasis cannot be assessed,Stage 1,N,2
10331,4334000045,415504,2018-07-26,6327219,131809,PA,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
10332,4334000045,415504,2018-07-26,6327219,131811,FC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
10333,4334000045,415504,2018-07-26,6327219,131810,FA,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
10579,4334042489,428203,2018-06-12,45043237,129072,HY,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
10580,4334042489,428203,2018-06-12,45043237,129073,HY,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
10696,4334059057,415575,2018-12-27,6210698,131847,FC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
10697,4334059057,415575,2018-12-27,6210698,131846,HE,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
10854,4334097650,415332,2019-01-14,6186282,132003,DCH,MALIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
10855,4334097650,415332,2019-01-14,6186282,132004,II,MALIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
12082,4334321340,77712,2015-04-28,8206476,80794,AB,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
12083,4334321340,77712,2015-04-28,8206476,80523,SE,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
12084,4334321340,77711,2015-04-28,8206476,80793,AB,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
12085,4334321340,77711,2015-04-28,8206476,80524,SE,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
14028,4334477697,437382,2017-10-27,3916434,121944,PTB,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
14029,4334477697,437382,2017-10-27,3916434,119930,PSH,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
14287,4334505164,428701,2017-11-17,45445170,129583,FC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
14288,4334505164,428701,2017-11-17,45445170,129582,FC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
15473,4334892163,429716,2018-08-13,6126661,128567,FA,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
15474,4334892163,429716,2018-08-13,6126661,128566,FC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
15953,4335112235,436713,2017-12-22,1263578,125314,ADH,HIGHRISK,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
15954,4335112235,436713,2017-12-22,1263578,121504,FEA,HIGHRISK,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
16507,4335422668,459617,2016-12-27,8076031,98553,ID,MALIGN,7.0,NaN,Pathologic,G2,4.0,0.0,NaN,P,P,P,Tumor more than 0.5 cm but not more than 1 cm ...,No regional lymph node metastasis,Distant metastasis cannot be assessed,Stage 1,N,2
16508,4335422668,459617,2016-12-27,8076031,98902,II,MALIGN,7.0,7.0,Pathologic,G2,4.0,0.0,NaN,P,P,P,Tumor more than 0.5 cm but not more than 1 cm ...,No regional lymph node metastasis,Distant metastasis cannot be assessed,Stage 1,N,2
17253,4335787606,458510,2017-01-10,44879028,98650,AD,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
17254,4335787606,458510,2017-01-10,44879028,98651,FC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
17824,4336276185,426360,2018-12-28,3682501,167355,IL,MALIGN,28.0,NaN,Pathologic,G3,7.0,0.0,U,P,P,N,Tumor more than 2 cm but not more than 5 cm in...,No regional lymph node metastasis histological...,No distant metastasis,Stage 2A,N,2
17825,4336276185,426360,2018-12-28,3682501,131046,ID,MALIGN,28.0,NaN,Pathologic,G3,7.0,1.0,U,P,P,N,Tumor more than 2 cm but not more than 5 cm in...,No regional lymph node metastasis histological...,No distant metastasis,Stage 2A,N,2
18062,4337560066,415301,2018-10-05,6839786,132039,FA,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
18063,4337560066,415301,2018-10-05,6839786,132038,AD,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2

In [21]:
unique_df = final_df.drop_duplicates(subset=final_df.columns.tolist(), keep = 'first').reset_index(drop = True)

In [22]:
unique_df

,PATIENT_STUDY_ID,BX_ID,PATHOLOGY_DATE,PATIENT_ID,FINDING_ID,PATHOLOGY_CD,LESION_CLASS,FINDING_SIZE_1,FINDING_SIZE_2,MEASUREMENT_TYPE,HISTROLOGY_GRADE,NODES_REMOVED,NODES_POSITIVE,MARGIN_STATUS,ESTROGEN_RECEPTOR,PROGESTERONE_RECEPTOR,HER2NEU,STAGE_T,STAGE_N,STAGE_M,STAGE_NUM,NIPPLE_INVOLVED
0,4330018595,487690,2020-06-05,9654707,168529,ID,MALIGN,30.0,NaN,Pathologic,G2,2.0,0.0,NaN,P,P,N,Tumor more than 1 cm but not more than 2 cm in...,No regional lymph node metastasis,No distant metastasis,Stage 1,N
1,4330018595,487690,2020-06-05,9654707,168529,DCI,MALIGN,30.0,NaN,Pathologic,G2,2.0,0.0,NaN,P,P,N,Tumor more than 1 cm but not more than 2 cm in...,No regional lymph node metastasis,No distant metastasis,Stage 1,N
2,4330018595,475789,2020-07-28,9654707,170446,II,MALIGN,30.0,NaN,Pathologic,G2,2.0,0.0,NaN,P,P,N,Tumor more than 1 cm but not more than 2 cm in...,No regional lymph node metastasis,No distant metastasis,Stage 1,N
3,4330029102,477464,2021-05-10,7939240,177674,FC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
4,4330044371,467808,2022-05-23,2438374,188141,FC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18344,4339933706,449749,2017-07-25,43137037,108450,IP,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
18345,4339943307,410232,2019-06-25,43135668,136168,FA,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
18346,4339945522,353888,2022-10-25,9099455,192141,ADH,HIGHRISK,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
18347,4339945522,350178,2022-12-15,9099455,194844,ADH,HIGHRISK,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
18348,4339959661,461902,2021-11-22,7269813,184076,FN,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N

In [23]:
# output_file = os.path.join("../Data/", study, "Cleaned", file + ".xlsx")
# final_df[extract_cols].to_excel(output_file, index=False)

output_file = os.path.join("../Data/", study, "Cleaned", file + ".xlsx")
unique_df[extract_cols].to_excel(output_file, index=False)

### Control

In [79]:
file_names = [
    str(file) + "_controls.txt", 
    str(file) + "_controls.csv",
]
file_names

['pathology_findings_controls.txt', 'pathology_findings_controls.csv']

In [80]:
study = "Control"
folder = ["R3_3787_Lee_Control_Extract_Files", "R3_3787_Lee_Data_Controls_20240508"]

In [81]:
final_unique_dfs = [] # List to hold the de-duplicated data from each file

# 2. Process each file
for i, file_name in enumerate(file_names):
    file_extension = os.path.splitext(file_name)[1].lower()
    file_path = os.path.join(shared_path, study, folder[i], file_name)
    
    if file_extension == '.csv':
        try:
            current_df = pd.read_csv(file_path, encoding='latin-1')
        except:
            print('file not exist in:', folder[i])
    elif file_extension == '.txt':
        try:
            current_df = pd.read_csv(file_path, sep='|')
        except:
            print('file not exist in:', folder[i])
    else:
        continue

    # --- KEY LOGIC FOR INTER-FILE DEDUPLICATION ---
    
    # Concatenate the current file's data with all previously processed data
    # (Do NOT use ignore_index=True here, we need separate indices for now)
    
    if final_unique_dfs:
        # Create a temporary DataFrame of ALL data processed so far
        all_prior_data = pd.concat(final_unique_dfs)
        
        # Check the current_df against all prior data. 
        # We only look at the columns that contain the actual data (excluding the index).
        data_columns = current_df.columns
        
        # Identify rows in the current file that are NOT duplicates of PRIOR files
        # The 'indicator=True' is used to identify the source of the merge
        try:
            merged = pd.merge(
                current_df, 
                all_prior_data, 
                on=list(data_columns), # Merge on all data columns
                how='left', 
                indicator=True
            )

            
            # Rows in the current file that are *only* in the 'left' (current_df) are unique
            unique_to_current_file = merged[merged['_merge'] == 'left_only'].drop(columns='_merge')

        except:
            merged = pd.concat((all_prior_data, current_df), ignore_index=True)
            unique_to_current_file = merged
            
        # Append the unique data (which includes any intra-file duplicates)
        final_unique_dfs.append(unique_to_current_file)
    else:
        # The first file is added as is (it has no prior files to check against)
        final_unique_dfs.append(current_df)


# 3. Final Concatenation
if final_unique_dfs:
    # Concatenate the final list of DataFrames to produce the result
    final_df = pd.concat(final_unique_dfs, ignore_index=True)

    print("✅ Successfully merged and removed ONLY inter-file duplicates.")
    print("\nFinal DataFrame head (includes intra-file duplicates):")
else:
    print("❌ No valid files were read. The final DataFrame is empty.")

✅ Successfully merged and removed ONLY inter-file duplicates.

Final DataFrame head (includes intra-file duplicates):

In [82]:
final_df

,PATIENT_STUDY_ID,BX_ID,PATHOLOGY_DATE,PATIENT_ID,FINDING_ID,PATHOLOGY_CD,LESION_CLASS,FINDING_SIZE_1,FINDING_SIZE_2,MEASUREMENT_TYPE,HISTROLOGY_GRADE,NODES_REMOVED,NODES_POSITIVE,MARGIN_STATUS,ESTROGEN_RECEPTOR,PROGESTERONE_RECEPTOR,HER2NEU,STAGE_T,STAGE_N,STAGE_M,STAGE_NUM,NIPPLE_INVOLVED
0,4333062366,475428,08/06/2020,2421647,169708,FC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
1,4333062366,471969,12/04/2020,2421647,174232,PA,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
2,4333373719,471830,10/29/2020,8400344,174261,BC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
3,4333373719,471839,10/29/2020,8400344,174262,BC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
4,4334928638,426146,01/02/2019,44319710,131172,AM,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
721,4333229846,351240,10/03/2022,9083419,193670,ID,MALIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
722,4333017529,467603,04/06/2022,9315511,188333,BC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
723,4335929637,466349,04/18/2022,8206626,188598,FC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
724,4333007393,466178,04/11/2022,3010324,188865,II,MALIGN,30.0,NaN,Pathologic,G3,NaN,NaN,NaN,P,P,N,Tumor more than 2 cm but not more than 5 cm in...,No regional lymph node metastasis,No distant metastasis,Stage 2A,N
725,4333422035,351381,12/22/2022,653324,193629,BC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N

In [83]:
final_df['PATHOLOGY_DATE'] = pd.to_datetime(final_df['PATHOLOGY_DATE'], format='%m/%d/%Y')
final_df['PATHOLOGY_DATE'] = final_df['PATHOLOGY_DATE'].dt.strftime('%Y-%m-%d')

In [84]:
final_df.sort_values(by=['PATIENT_STUDY_ID', 'PATHOLOGY_DATE', "BX_ID"], ascending=[True, True, False], inplace=True, ignore_index=True)

#### <span style="color: blue;">Remove duplicated entries, add a column marked how many duplicates </span> 

**Before drop duplicate = <span style="color: blue;">final_df</span> , after drop duplicate = <span style="color: blue;">unique_df</span>**

In [85]:
unique_df = final_df.copy()

In [86]:
unique_df['duplicate_count'] = unique_df.groupby(unique_df.columns.tolist(), dropna=False).transform('size')

In [87]:
unique_df = unique_df.drop_duplicates(subset=unique_df.columns.tolist(), keep = 'first').reset_index(drop = True)

In [88]:
unique_extract_cols = extract_cols + ['duplicate_count']

In [89]:
unique_df['duplicate_count'].unique()

array([1, 3, 2])

In [91]:
unique_df[unique_df['duplicate_count']!=1]

,PATIENT_STUDY_ID,BX_ID,PATHOLOGY_DATE,PATIENT_ID,FINDING_ID,PATHOLOGY_CD,LESION_CLASS,FINDING_SIZE_1,FINDING_SIZE_2,MEASUREMENT_TYPE,HISTROLOGY_GRADE,NODES_REMOVED,NODES_POSITIVE,MARGIN_STATUS,ESTROGEN_RECEPTOR,PROGESTERONE_RECEPTOR,HER2NEU,STAGE_T,STAGE_N,STAGE_M,STAGE_NUM,NIPPLE_INVOLVED,duplicate_count
27,4333008024,410317,2019-06-17,1174803,136092,AD,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
53,4333062366,475428,2020-08-06,2421647,169708,FC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
54,4333062366,471969,2020-12-04,2421647,174232,PA,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
79,4333101704,355101,2022-07-15,1192796,189825,BC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
145,4333373719,471839,2020-10-29,8400344,174262,BC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
146,4333373719,471830,2020-10-29,8400344,174261,BC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
161,4333488305,417825,2019-11-07,8194055,139586,BC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
165,4333514173,478396,2021-03-19,9687278,176762,AN,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
168,4333571001,427540,2018-11-12,8262906,129745,BC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
181,4333624870,469223,2022-02-21,9760831,185736,FC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
204,4333681110,418013,2019-09-30,8946447,138395,DHU,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
208,4333718747,469899,2022-03-08,1365474,186173,FC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
210,4333744639,79051,2015-01-20,2372944,78182,BC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
225,4333788435,464163,2021-09-10,2991281,180936,FF,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
228,4333816001,437619,2017-11-20,3632240,120595,BC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
229,4333816001,437618,2017-11-20,3632240,120596,BC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
259,4333923942,452408,2016-09-07,9869414,94739,IP,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
277,4333965597,454971,2016-07-14,3704855,93273,BC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
307,4334147637,442707,2017-06-01,8444940,105450,BC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
314,4334197267,354590,2022-06-29,8428410,190436,PSH,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
348,4334321340,77712,2015-04-28,8206476,80794,AB,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
349,4334321340,77712,2015-04-28,8206476,80523,SE,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
350,4334321340,77711,2015-04-28,8206476,80793,AB,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
351,4334321340,77711,2015-04-28,8206476,80524,SE,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
403,4334458096,352445,2022-10-25,2496219,192471,BC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
405,4334470850,427424,2018-05-30,1100984,129865,II,MALIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
406,4334470850,427420,2018-07-13,1100984,129870,II,MALIGN,40.0,NaN,Pathologic,G2,2.0,0.0,NaN,P,P,N,Tumor more than 2 cm but not more than 5 cm in...,No regional lymph node metastasis,No distant metastasis,Stage 2B,N,3
407,4334470850,420588,2018-07-13,1100984,126783,ADH,HIGHRISK,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
408,4334470850,427425,2018-09-04,1100984,129864,II,MALIGN,40.0,NaN,Pathologic,G2,2.0,0.0,NaN,P,P,N,Tumor more than 2 cm but not more than 5 cm in...,No regional lymph node metastasis,No distant metastasis,Stage 2B,N,3
425,4334712226,66877,2016-05-12,44259329,91385,BC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
426,4334733486,65354,2015-06-08,44391722,81884,FA,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
433,4334914209,437012,2017-10-04,44309839,120202,DHU,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
439,4334928638,426146,2019-01-02,44319710,131172,AM,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,2
466,4335115323,453998,2016-08-12,3984770,94252,ANM,MALIGN,53.0,NaN,Pathologic,G2,21.0,3.0,NaN,P,P,N,Tumor more than 5 cm in greatest dimension,Metastasis in 1 to 3 axillary lymph nodes and ...,Distant metastasis cannot be assessed,Stage 3A,N,3
467,4335115323,453998,2016-08-12,3984770,94252,II,MALIGN,53.0,NaN,Pathologic,G2,21.0,3.0,NaN,P,P,N,Tumor more than 5 cm in greatest dimension,Metastasis in 1 to 3 axillary lymph nodes and ...,Distant metastasis cannot be assessed,Stage 3A,N,3
468,4335115323,457067,2017-02-07,3984770,100227,II,MALIGN,53.0,NaN,Pathologic,G2,21.0,3.0,NaN,P,P,N,Tumor more than 5 cm in greatest dimension,Metastasis in 1 to 3 axillary lymph nodes and ...,Distant metastasis cannot be assessed,Stage 3A,N,3
470,4335145025,76663,2015-04-17,44341850,81674,IP,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
471,4335160191,450680,2016-12-01,8453785,97580,II,MALIGN,8.0,NaN,Pathologic,G3,2.0,2.0,NaN,P,P,P,Tumor more than 0.5 cm but not more than 1 cm ...,Metastasis in 1 to 3 axillary lymph nodes,Distant metastasis cannot be assessed,Stage 2A,N,3
472,4335170472,454563,2016-06-23,43440389,92681,ID,MALIGN,110.0,NaN,Pathologic,G3,4.0,1.0,NaN,P,P,P,Tumor more than 2 cm but not more than 5 cm in...,Metastasis to movable ipsilateral axillary lym...,No distant metastasis,Stage 2B,N,3
473,4335170472,454563,2016-06-23,43440389,92681,II,MALIGN,110.0,NaN,Pathologic,G3,4.0,1.0,NaN,P,P,P,Tumor more than 2 cm but not more than 5 cm in...,Metastasis to movable ipsilateral axillary lym...,No distant metastasis,Stage 2B,N,3
474,4335170472,454562,2016-06-23,43440389,92682,II,MALIGN,110.0,NaN,Pathologic,G3,4.0,1.0,NaN,P,P,P,Tumor more than 2 cm but not more than 5 cm in...,Metastasis to movable ipsilateral axillary lym...,No distant metastasis,Stage 2B,N,3
475,4335170472,454561,2016-06-23,43440389,92683,FC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
476,4335170472,454560,2016-06-23,43440389,92684,MAN,MALIGN,NaN,NaN,NaN,GX,4.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
477,4335170472,459965,2016-12-20,43440389,98301,II,MALIGN,110.0,NaN,Pathologic,G3,4.0,1.0,NaN,P,P,P,Tumor more than 2 cm but not more than 5 cm in...,Metastasis to movable ipsilateral axillary lym...,No distant metastasis,Stage 2B,N,3
515,4335453933,423511,2018-01-17,44314337,123723,BC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
516,4335453933,423510,2018-01-17,44314337,123724,BC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
522,4335501462,429258,2018-07-27,2727716,128020,DCI,MALIGN,NaN,NaN,Pathologic,G2,NaN,NaN,NaN,NaN,NaN,NaN,Ductal carcinoma in situ,"Regional lymph nodes cannot be assessed (e.g.,...",Distant metastasis cannot be assessed,Stage 0,N,3
523,4335501462,429257,2018-07-27,2727716,128021,ADH,HIGHRISK,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
524,4335501462,428785,2018-10-30,2727716,129599,DCL,MALIGN,NaN,NaN,Pathologic,G1,NaN,NaN,NaN,NaN,NaN,NaN,Ductal carcinoma in situ,No regional lymph node metastasis,Distant metastasis cannot be assessed,Stage 0,N,3
536,4335639335,436686,2018-01-08,6283697,121643,BC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
537,4335640729,449987,2017-08-03,45093958,108310,FF,BENIGN,13.0,12.0,NaN,GX,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
574,4335803122,412669,2015-02-11,43524893,134831,BC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
582,4335904114,64883,2015-07-07,8144281,83431,FC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3
588,4335926821,68653,2015-12-07,1260129,89509,II,MALIGN,1.2,NaN,Pathologic,G3,1.0,0.0,NaN,P,P,NaN,Tumor more than 1 cm but not more than 2 cm in...,No regional lymph node metastasis,Distant metastasis cannot be assessed,Stage 1,N,2
589,4335929637,466349,2022-04-18,8206626,188598,FC,BENIGN,NaN,NaN,NaN,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,3

In [92]:
unique_df = final_df.drop_duplicates(subset=final_df.columns.tolist(), keep = 'first').reset_index(drop = True)

In [93]:
unique_df[extract_cols]

,PATIENT_STUDY_ID,BX_ID,PATHOLOGY_DATE,LESION_CLASS,PATHOLOGY_CD,HISTROLOGY_GRADE,ESTROGEN_RECEPTOR,PROGESTERONE_RECEPTOR,HER2NEU,STAGE_T,STAGE_N,STAGE_M,STAGE_NUM,MARGIN_STATUS
0,4330189702,418851,2019-04-26,MALIGN,ID,G2,P,P,N,Tumor more than 1 cm but not more than 2 cm in...,Metastasis in 1 to 3 axillary lymph nodes,Distant metastasis cannot be assessed,Stage 2A,NaN
1,4330311096,450823,2016-11-10,MALIGN,ID,G2,P,P,N,Tumor more than 1 cm but not more than 2 cm in...,No regional lymph node metastasis,Distant metastasis cannot be assessed,Stage 1,NaN
2,4330311096,450823,2016-11-10,MALIGN,II,G2,P,P,N,Tumor more than 1 cm but not more than 2 cm in...,No regional lymph node metastasis,Distant metastasis cannot be assessed,Stage 1,NaN
3,4330311096,459526,2016-11-28,MALIGN,II,G2,P,P,NaN,Tumor more than 1 cm but not more than 2 cm in...,No regional lymph node metastasis,Distant metastasis cannot be assessed,Stage 1,NaN
4,4330329490,437485,2017-10-25,BENIGN,IP,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
617,4337609101,406901,2015-08-20,BENIGN,FF,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
618,4337636503,406140,2015-03-09,BENIGN,FNS,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
619,4337689949,420192,2018-08-02,BENIGN,FC,GX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
620,4337793359,414656,2019-01-18,MALIGN,ID,G2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
621,4337793359,413919,2019-02-27,MALIGN,ID,G2,P,P,N,Tumor more than 1 cm but not more than 2 cm in...,No regional lymph node metastasis,Distant metastasis cannot be assessed,Stage 1,NaN

In [94]:
# output_file = os.path.join("../Data/", study, "Cleaned", file + ".xlsx")
# final_df[extract_cols].to_excel(output_file, index=False)

output_file = os.path.join("../Data/", study, "Cleaned", file + ".xlsx")
unique_df[extract_cols].to_excel(output_file, index=False)